name: nonsense_spectrum
description: >
  A rainbow of Color and Gradient utilities. Interpolate gradients with a
  realized GradientTween. New type Steps & shaded varieties. Color generation &
  operators.

version: 1.0.0
repository: https://github.com/Zabadam/spectrum
issue_tracker: https://github.com/Zabadam/spectrum/issues

environment:
  sdk: ^3.3.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.1.1
