name: spectrum
description: >
  A rainbow of Color and Gradient utilities; including GradientTweens,
  Gradient.copyWith(), Steps-type gradients, Color.generateComplements(),
  AnimatedGradients, MaterialColor generation, and more!

version: 0.2.0
repository: https://github.com/Zabadam/spectrum
issue_tracker: https://github.com/Zabadam/spectrum/issues

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: null

flutter: null
